name = "orin's pack"
version = "1.0.0"
author = "hakureiyukari01@gmail.com"
category = "misc"
description = "阿燐在她的猫车中找到一个神秘压缩包"

# Optional: 显式 safe_name；缺省由 name 派生（派生失败时必须显式提供）
# safe_name = "xxx"

attachment = "attachment/orin.zip"

[flag]
type = "static"
value = "flag{komachi-53089-suki-1547563}"
