name = "strings_attached2"
version = "1.0.0"
author = "ablklice@gmail.com"
category = "reverse"
description = "和某一道题加密算法一样，但好像又有一些不同"

# Optional: 显式 safe_name；缺省由 name 派生（派生失败时必须显式提供）
# safe_name = "xxx"

attachment = "attachment/strings_attached2.exe"

[flag]
type = "static"
value = "flag{YOU_FIND_IT_HAHA}"
