#!/usr/bin/env python3
"""Unit tests for ``scripts/content.py``.

Run with::

    python3 -m unittest discover -s scripts/tests -v

The tests only use fixtures below ``scripts/tests/fixtures``; production
content is never required.
"""

from __future__ import annotations

import contextlib
import importlib.util
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

TESTS_DIR = Path(__file__).resolve().parent
SCRIPTS_DIR = TESTS_DIR.parent
FIXTURES_DIR = TESTS_DIR / "fixtures"
VALID_FIXTURE = FIXTURES_DIR / "valid"
INVALID_FIXTURE = FIXTURES_DIR / "invalid"
SAFE_NAMES_FIXTURE = FIXTURES_DIR / "safe-names"

#: Keys that must never be exported into catalog.json.
FORBIDDEN_CATALOG_KEYS = {
    "value",
    "flag_value",
    "template",
    "secret",
    "token",
    "password",
    "env",
    "solution",
}

CONTENT_META_TEMPLATE = """\
name = "{name}"
version = "1.0.0"
author = "dev@floatctf.local"
category = "web"
difficulty = "easy"
tags = []
description = "generated by tests"
{safe_name}
"""


def _load_content_module():
    spec = importlib.util.spec_from_file_location(
        "floatctf_content", SCRIPTS_DIR / "content.py"
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["floatctf_content"] = module
    spec.loader.exec_module(module)
    return module


content = _load_content_module()


def quiet(function, *args, **kwargs):
    """Call *function* while swallowing stdout/stderr."""

    with contextlib.redirect_stdout(io.StringIO()):
        with contextlib.redirect_stderr(io.StringIO()):
            return function(*args, **kwargs)


def copy_fixture(fixture: Path, destination: Path) -> Path:
    shutil.copytree(fixture, destination, dirs_exist_ok=True)
    return destination


def write_content(
    root: Path,
    kind: str,
    content_id: str,
    *,
    safe_name: str | None = None,
    dockerfile: bool = False,
) -> Path:
    """Create a minimal content directory below *root* (kind: challenges/...)."""

    directory = root / kind / content_id
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "meta.toml").write_text(
        CONTENT_META_TEMPLATE.format(
            name=content_id,
            safe_name=f'safe_name = "{safe_name}"' if safe_name else "",
        ),
        encoding="utf-8",
    )

    if dockerfile:
        source = directory / "src"
        source.mkdir(parents=True, exist_ok=True)
        (source / "Dockerfile").write_text("FROM scratch\n", encoding="utf-8")

    return directory


def find_entry(entries: list[dict], content_id: str) -> dict:
    for entry in entries:
        if entry["id"] == content_id:
            return entry
    raise AssertionError(f"{content_id!r} missing")


def json_keys(node) -> set[str]:
    """Collect every dict key used anywhere in *node*."""

    keys: set[str] = set()

    if isinstance(node, dict):
        for key, value in node.items():
            keys.add(key)
            keys |= json_keys(value)
    elif isinstance(node, list):
        for item in node:
            keys |= json_keys(item)

    return keys


# ---------------------------------------------------------------------------
# 1. image naming
# ---------------------------------------------------------------------------


class ImageRefTests(unittest.TestCase):
    def _content(self, content_type: str, version: str = "1.0.0"):
        return content.Content(
            id="comment",
            type=content_type,
            path=Path("challenges/comment"),
            meta={"version": version},
        )

    def test_challenge_image_ref(self) -> None:
        self.assertEqual(
            content.image_ref(self._content(content.CONTENT_CHALLENGE)),
            "floatctf/comment:challenge-v1.0.0",
        )

    def test_gamebox_image_ref(self) -> None:
        self.assertEqual(
            content.image_ref(self._content(content.CONTENT_GAMEBOX, "1.2.0")),
            "floatctf/comment:gamebox-v1.2.0",
        )

    def test_image_ref_from_fixture(self) -> None:
        challenges = content.scan_contents(
            VALID_FIXTURE, content.CONTENT_CHALLENGE
        )
        gameboxes = content.scan_contents(VALID_FIXTURE, content.CONTENT_GAMEBOX)

        self.assertEqual(
            [content.image_ref(item) for item in challenges],
            [
                "floatctf/comment:challenge-v1.0.0",
                "floatctf/cookie:challenge-v1.0.0",
            ],
        )
        self.assertEqual(
            [content.image_ref(item) for item in gameboxes],
            ["floatctf/comment:gamebox-v1.0.0"],
        )

    def test_image_metadata_paths(self) -> None:
        challenge = content.load_content(VALID_FIXTURE, "challenges/comment")
        gamebox = content.load_content(VALID_FIXTURE, "gameboxes/comment")

        self.assertEqual(
            content.image_context(challenge),
            ("challenges/comment/src", "challenges/comment/src/Dockerfile"),
        )
        self.assertEqual(
            content.image_context(gamebox),
            ("gameboxes/comment/src", "gameboxes/comment/src/Dockerfile"),
        )

    def test_image_meta_requires_dockerfile(self) -> None:
        with self.assertRaises(SystemExit) as raised:
            quiet(
                content.main,
                ["image-meta", "challenges/cookie", "--root", str(VALID_FIXTURE)],
            )

        self.assertEqual(raised.exception.code, 1)


# ---------------------------------------------------------------------------
# Docker safe_name: derivation, override and conflicts
# ---------------------------------------------------------------------------


class SafeNameTests(unittest.TestCase):
    def fixture_challenges(self) -> dict[str, "content.Content"]:
        return {
            item.id: item
            for item in content.scan_contents(
                SAFE_NAMES_FIXTURE, content.CONTENT_CHALLENGE
            )
        }

    def fixture_gameboxes(self) -> dict[str, "content.Content"]:
        return {
            item.id: item
            for item in content.scan_contents(
                SAFE_NAMES_FIXTURE, content.CONTENT_GAMEBOX
            )
        }

    def test_derive_simple(self) -> None:
        self.assertEqual(content.derive_safe_name("comment"), "comment")

    def test_derive_uppercase(self) -> None:
        self.assertEqual(
            content.derive_safe_name("Android_reverse"), "android_reverse"
        )

    def test_derive_uppercase_and_dash(self) -> None:
        self.assertEqual(
            content.derive_safe_name("FloatCTF-qidong"), "floatctf-qidong"
        )

    def test_derive_apostrophe(self) -> None:
        self.assertEqual(
            content.derive_safe_name("Cirno's perfect math class"),
            "cirnos-perfect-math-class",
        )
        self.assertEqual(
            content.derive_safe_name("Cirno\u2019s book"), "cirnos-book"
        )

    def test_derive_whitespace(self) -> None:
        self.assertEqual(content.derive_safe_name("foo bar"), "foo-bar")
        self.assertEqual(content.derive_safe_name("foo   bar"), "foo-bar")

    def test_derive_normalizes_separators(self) -> None:
        self.assertEqual(content.derive_safe_name("foo__bar"), "foo-bar")
        self.assertEqual(content.derive_safe_name("--Foo..Bar--"), "foo-bar")
        self.assertEqual(content.derive_safe_name("foo.bar"), "foo.bar")

    def test_derive_returns_empty_for_unicode_only_ids(self) -> None:
        self.assertEqual(content.derive_safe_name("题目"), "")

    def test_derive_matches_docker_repository_pattern(self) -> None:
        for content_id in (
            "comment",
            "Android_reverse",
            "FloatCTF-qidong",
            "Cirno's perfect math class",
            "komachi's book",
            "orin's pack",
            "Flag_in_the_model",
        ):
            derived = content.derive_safe_name(content_id)
            self.assertTrue(
                content.SAFE_NAME_PATTERN.match(derived),
                f"{content_id!r} derived to invalid {derived!r}",
            )

    def test_explicit_safe_name_wins(self) -> None:
        item = content.Content(
            id="Cirno's perfect math class",
            type=content.CONTENT_CHALLENGE,
            path=Path("challenges/Cirno's perfect math class"),
            meta={"safe_name": "custom-name"},
        )

        self.assertEqual(item.safe_name, "custom-name")

    def test_explicit_safe_name_for_unicode_id(self) -> None:
        item = content.Content(
            id="题目",
            type=content.CONTENT_CHALLENGE,
            path=Path("challenges/题目"),
            meta={"safe_name": "challenge-001"},
        )

        self.assertEqual(item.safe_name, "challenge-001")

    def test_fixture_safe_names(self) -> None:
        challenges = self.fixture_challenges()

        self.assertEqual(challenges["Android_reverse"].safe_name, "android_reverse")
        self.assertEqual(
            challenges["FloatCTF-qidong"].safe_name, "floatctf-qidong"
        )
        self.assertEqual(
            challenges["Cirno's perfect math class"].safe_name,
            "cirnos-perfect-math-class",
        )
        self.assertEqual(challenges["题目"].safe_name, "challenge-001")
        self.assertTrue(content.validate(SAFE_NAMES_FIXTURE).ok)

    def test_image_ref_uses_safe_name(self) -> None:
        challenges = self.fixture_challenges()

        self.assertEqual(
            content.image_ref(challenges["FloatCTF-qidong"]),
            "floatctf/floatctf-qidong:challenge-v1.0.0",
        )
        self.assertEqual(
            content.image_ref(challenges["题目"]),
            "floatctf/challenge-001:challenge-v2.0.0",
        )

    def test_challenge_and_gamebox_may_share_safe_name(self) -> None:
        challenge = self.fixture_challenges()["Android_reverse"]
        gamebox = self.fixture_gameboxes()["Android_reverse"]

        self.assertEqual(challenge.safe_name, gamebox.safe_name)
        self.assertEqual(challenge.safe_name, "android_reverse")
        self.assertNotEqual(
            content.image_ref(challenge), content.image_ref(gamebox)
        )

    def test_image_ref_rejects_underivable_safe_name(self) -> None:
        item = content.Content(
            id="题目",
            type=content.CONTENT_CHALLENGE,
            path=Path("challenges/题目"),
            meta={"version": "1.0.0"},
        )

        with self.assertRaises(content.ContentError) as raised:
            content.image_ref(item)

        self.assertIn("unable to derive Docker safe_name", str(raised.exception))

    def test_image_ref_rejects_invalid_safe_name(self) -> None:
        item = content.Content(
            id="comment",
            type=content.CONTENT_CHALLENGE,
            path=Path("challenges/comment"),
            meta={"version": "1.0.0", "safe_name": "Foo Bar"},
        )

        with self.assertRaises(content.ContentError) as raised:
            content.image_ref(item)

        self.assertIn("invalid safe_name", str(raised.exception))


# ---------------------------------------------------------------------------
# 2 - 5. validation
# ---------------------------------------------------------------------------


class ValidateTests(unittest.TestCase):
    def errors(self, root: Path) -> list[str]:
        return content.validate(root).errors

    def test_valid_fixture(self) -> None:
        result = content.validate(VALID_FIXTURE)

        self.assertTrue(result.ok, result.errors)
        self.assertEqual(len(result.challenges), 2)
        self.assertEqual(len(result.gameboxes), 1)
        self.assertEqual(len(result.events), 1)

    def test_missing_field(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "challenges/broken_missing_difficulty/meta.toml: "
            "missing field 'difficulty'",
            errors,
        )

    def test_invalid_version(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "challenges/broken_version/meta.toml: "
            "invalid version '1.0' (expected x.y.z)",
            errors,
        )

    def test_invalid_difficulty(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "challenges/broken_difficulty/meta.toml: "
            "invalid difficulty 'impossible' "
            "(expected one of unknown, beginner, easy, medium, hard, expert)",
            errors,
        )

    def test_invalid_port(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "challenges/broken_docker/meta.toml: "
            "invalid docker.port 70000 (expected 1..65535)",
            errors,
        )

    def test_invalid_tags(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "challenges/broken_docker/meta.toml: "
            "field 'tags' must be an array of non-empty strings",
            errors,
        )

    def test_invalid_recommended_resources(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "challenges/broken_docker/meta.toml: "
            "invalid docker.recommended_resources.cpu_millis 0 "
            "(expected a positive integer)",
            errors,
        )
        self.assertIn(
            "challenges/broken_docker/meta.toml: "
            "invalid docker.recommended_resources.pids_limit -1 "
            "(expected a positive integer)",
            errors,
        )

    def test_missing_meta_toml(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "challenges/broken_no_meta/meta.toml: missing meta.toml",
            errors,
        )

    def test_unknown_event_references(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "events/freshcup.toml: unknown challenge 'ghost'",
            errors,
        )
        self.assertIn(
            "events/freshcup.toml: unknown gamebox 'ghostbox'",
            errors,
        )

    def test_all_difficulties_are_accepted(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = copy_fixture(VALID_FIXTURE, Path(tmp) / "content")
            meta_path = root / "challenges" / "comment" / "meta.toml"
            original = meta_path.read_text(encoding="utf-8")

            for difficulty in content.DIFFICULTIES:
                meta_path.write_text(
                    original.replace(
                        'difficulty = "easy"', f'difficulty = "{difficulty}"'
                    ),
                    encoding="utf-8",
                )
                self.assertTrue(
                    content.validate(root).ok,
                    f"difficulty '{difficulty}' should be accepted",
                )

    def test_empty_accounts_for_missing_directories(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            result = content.validate(Path(tmp))

            self.assertTrue(result.ok, result.errors)
            self.assertEqual(
                (len(result.challenges), len(result.gameboxes), len(result.events)),
                (0, 0, 0),
            )

    def test_invalid_explicit_safe_name(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "challenges/broken_safe_name/meta.toml: invalid safe_name 'Foo Bar'",
            errors,
        )

    def test_underivable_safe_name_requires_explicit_value(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn(
            "challenges/题目/meta.toml: unable to derive Docker safe_name; "
            "set safe_name explicitly",
            errors,
        )

    def test_explicit_safe_name_makes_unicode_id_valid(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = copy_fixture(SAFE_NAMES_FIXTURE, Path(tmp) / "content")

            self.assertTrue(content.validate(root).ok, content.validate(root).errors)

            meta_path = root / "challenges" / "题目" / "meta.toml"
            meta_path.write_text(
                meta_path.read_text(encoding="utf-8").replace(
                    'safe_name = "challenge-001"\n', ""
                ),
                encoding="utf-8",
            )

            self.assertIn(
                "challenges/题目/meta.toml: unable to derive Docker safe_name; "
                "set safe_name explicitly",
                content.validate(root).errors,
            )

    def test_duplicate_safe_name_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp) / "content"
            write_content(root, "challenges", "Foo")
            write_content(root, "challenges", "foo")

            self.assertIn(
                "duplicate challenge safe_name 'foo': 'Foo' and 'foo'",
                content.validate(root).errors,
            )

    def test_duplicate_safe_name_across_types_is_allowed(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp) / "content"
            write_content(root, "challenges", "foo")
            write_content(root, "gameboxes", "foo")

            result = content.validate(root)

            self.assertTrue(result.ok, result.errors)

    def test_duplicate_event_references(self) -> None:
        errors = self.errors(INVALID_FIXTURE)

        self.assertIn("events/dup.toml: duplicate challenge 'broken_version'", errors)
        self.assertIn("events/dup.toml: duplicate gamebox 'box'", errors)


# ---------------------------------------------------------------------------
# 6 - 9. catalog
# ---------------------------------------------------------------------------


class CatalogTests(unittest.TestCase):
    def catalog(self) -> dict:
        return content.build_catalog(VALID_FIXTURE)

    def entry(self, collection: str, content_id: str) -> dict:
        for item in self.catalog()[collection]:
            if item["id"] == content_id:
                return item
        raise AssertionError(f"{collection}/{content_id} missing from catalog")

    def test_catalog_root_structure(self) -> None:
        catalog = self.catalog()

        self.assertEqual(
            list(catalog.keys()),
            ["version", "challenges", "gameboxes", "events"],
        )
        self.assertEqual(catalog["version"], 1)

    def test_catalog_challenge_generation(self) -> None:
        self.assertEqual(
            self.entry("challenges", "comment"),
            {
                "id": "comment",
                "name": "comment",
                "version": "1.0.0",
                "author": "fb0sh@outlook.com",
                "category": "web",
                "difficulty": "easy",
                "tags": ["php", "web"],
                "description": "注释里面有什么？",
                "image": "floatctf/comment:challenge-v1.0.0",
                "flag": {"type": "dynamic"},
                "docker": {
                    "port": 80,
                    "recommended_resources": {
                        "cpu_millis": 500,
                        "memory_bytes": 268435456,
                        "pids_limit": 100,
                    },
                },
                "events": ["freshcup"],
            },
        )

    def test_catalog_gamebox_generation(self) -> None:
        self.assertEqual(
            self.entry("gameboxes", "comment"),
            {
                "id": "comment",
                "name": "comment",
                "version": "1.0.0",
                "author": "dev@floatctf.local",
                "category": "misc",
                "difficulty": "medium",
                "tags": ["box"],
                "description": "GameBox fixture",
                "image": "floatctf/comment:gamebox-v1.0.0",
                "docker": {"port": 8080},
                "events": ["freshcup"],
            },
        )

    def test_catalog_challenge_without_events_or_docker(self) -> None:
        # No src/Dockerfile means attachment-only content: no image field.
        self.assertEqual(
            self.entry("challenges", "cookie"),
            {
                "id": "cookie",
                "name": "cookie",
                "version": "1.0.0",
                "author": "dev@floatctf.local",
                "category": "web",
                "difficulty": "unknown",
                "tags": [],
                "description": "想成为管理员吗？也许你需要一个特殊的饼干！",
                "flag": {"type": "static"},
                "events": [],
            },
        )

    def test_catalog_event_entry(self) -> None:
        self.assertEqual(
            self.catalog()["events"],
            [
                {
                    "id": "freshcup",
                    "title": "Freshcup Fixture",
                    "description": "Fixture event",
                    "started_at": "2025-01-01 10:00",
                    "ended_at": "2025-01-01 18:00",
                    "challenges": ["comment"],
                    "gameboxes": ["comment"],
                }
            ],
        )

    def test_event_to_challenge_reverse_relation(self) -> None:
        catalog = self.catalog()

        comment_challenge = self.entry("challenges", "comment")
        comment_gamebox = self.entry("gameboxes", "comment")

        self.assertEqual(comment_challenge["events"], ["freshcup"])
        self.assertEqual(comment_gamebox["events"], ["freshcup"])

        # An event only lists what it references.
        self.assertEqual(catalog["events"][0]["challenges"], ["comment"])
        self.assertEqual(catalog["events"][0]["gameboxes"], ["comment"])

    def test_catalog_never_exposes_flag_values(self) -> None:
        catalog = self.catalog()
        rendered = content.render_catalog(catalog)

        for entry in [*catalog["challenges"], *catalog["gameboxes"]]:
            if "flag" in entry:
                self.assertEqual(set(entry["flag"]), {"type"})

        self.assertFalse(FORBIDDEN_CATALOG_KEYS & json_keys(catalog))
        self.assertNotIn("fixture-flag-must-not-leak", rendered)

    def test_container_challenge_has_image_in_catalog(self) -> None:
        catalog = content.build_catalog(SAFE_NAMES_FIXTURE)

        self.assertEqual(
            find_entry(catalog["challenges"], "FloatCTF-qidong")["image"],
            "floatctf/floatctf-qidong:challenge-v1.0.0",
        )
        self.assertEqual(
            find_entry(catalog["challenges"], "题目")["image"],
            "floatctf/challenge-001:challenge-v2.0.0",
        )

    def test_static_challenge_has_no_image_in_catalog(self) -> None:
        catalog = content.build_catalog(SAFE_NAMES_FIXTURE)
        entry = find_entry(catalog["challenges"], "Android_reverse")

        self.assertNotIn("image", entry)
        self.assertIsNone(entry.get("image"))
        self.assertNotIn('"image": null', content.render_catalog(catalog))
        self.assertEqual(entry["id"], "Android_reverse")

    def test_catalog_image_matches_dockerfile_and_pattern(self) -> None:
        catalog = content.build_catalog(SAFE_NAMES_FIXTURE)
        image_pattern = re.compile(
            r"^floatctf/[a-z0-9]+(?:[._-][a-z0-9]+)*"
            r":(?:challenge|gamebox)-v\d+\.\d+\.\d+$"
        )

        for kind, entries in (
            ("challenges", catalog["challenges"]),
            ("gameboxes", catalog["gameboxes"]),
        ):
            for entry in entries:
                dockerfile = (
                    SAFE_NAMES_FIXTURE
                    / kind
                    / entry["id"]
                    / "src"
                    / "Dockerfile"
                )

                if "image" in entry:
                    self.assertTrue(dockerfile.is_file(), entry["id"])
                    self.assertRegex(entry["image"], image_pattern)
                else:
                    self.assertFalse(dockerfile.is_file(), entry["id"])

    def test_catalog_keeps_raw_id_and_unicode_description(self) -> None:
        catalog = content.build_catalog(SAFE_NAMES_FIXTURE)
        rendered = content.render_catalog(catalog)

        self.assertEqual(
            [item["id"] for item in catalog["challenges"]],
            sorted(item["id"] for item in catalog["challenges"]),
        )
        self.assertIn("题目", rendered)
        self.assertIn("Unicode id needs an explicit safe_name", rendered)

    def test_catalog_is_deterministic(self) -> None:
        first = content.render_catalog(content.build_catalog(VALID_FIXTURE))
        second = content.render_catalog(content.build_catalog(VALID_FIXTURE))

        self.assertEqual(first, second)
        self.assertTrue(first.endswith("\n"))
        self.assertNotIn("generated_at", first)

        catalog = self.catalog()
        self.assertEqual(
            [item["id"] for item in catalog["challenges"]],
            sorted(item["id"] for item in catalog["challenges"]),
        )
        self.assertEqual(
            [item["id"] for item in catalog["gameboxes"]],
            sorted(item["id"] for item in catalog["gameboxes"]),
        )
        self.assertEqual(
            [item["id"] for item in catalog["events"]],
            sorted(item["id"] for item in catalog["events"]),
        )

    def test_catalog_check_detects_missing_and_stale_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = copy_fixture(VALID_FIXTURE, Path(tmp) / "content")

            self.assertEqual(quiet(content.main, ["catalog", "--check", "--root", str(root)]), 1)

            self.assertEqual(quiet(content.main, ["catalog", "--root", str(root)]), 0)
            self.assertEqual(quiet(content.main, ["catalog", "--check", "--root", str(root)]), 0)

            (root / "catalog.json").write_text("{}\n", encoding="utf-8")
            self.assertEqual(quiet(content.main, ["catalog", "--check", "--root", str(root)]), 1)

    def test_catalog_round_trips_through_json(self) -> None:
        rendered = content.render_catalog(content.build_catalog(VALID_FIXTURE))

        self.assertEqual(
            json.loads(rendered),
            content.build_catalog(VALID_FIXTURE),
        )
        self.assertIn("注释里面有什么？", rendered)

    def test_catalog_output_writes_to_another_path(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = copy_fixture(VALID_FIXTURE, Path(tmp) / "content")
            target = Path(tmp) / "out" / "catalog.json"

            result = quiet(
                content.main,
                ["catalog", "--output", str(target), "--root", str(root)],
            )

            self.assertEqual(result, 0)
            self.assertTrue(target.is_file())
            self.assertFalse((root / "catalog.json").exists())
            self.assertEqual(
                target.read_text(encoding="utf-8"),
                content.render_catalog(content.build_catalog(root)),
            )

    def test_catalog_check_and_output_are_mutually_exclusive(self) -> None:
        with self.assertRaises(SystemExit) as raised:
            quiet(
                content.main,
                [
                    "catalog",
                    "--check",
                    "--output",
                    "/tmp/never-written.json",
                    "--root",
                    str(VALID_FIXTURE),
                ],
            )

        self.assertEqual(raised.exception.code, 2)

    def test_catalog_refuses_invalid_content(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = copy_fixture(INVALID_FIXTURE, Path(tmp) / "content")

            self.assertEqual(
                quiet(content.main, ["catalog", "--root", str(root)]), 1
            )
            self.assertFalse((root / "catalog.json").exists())


# ---------------------------------------------------------------------------
# labels / github output
# ---------------------------------------------------------------------------


class LabelTests(unittest.TestCase):
    def test_image_labels(self) -> None:
        challenge = content.load_content(VALID_FIXTURE, "challenges/comment")

        with mock.patch.dict(os.environ, {}, clear=True):
            labels = content.image_labels(challenge)

        self.assertEqual(
            labels,
            {
                "org.opencontainers.image.title": "comment",
                "org.opencontainers.image.description": "注释里面有什么？",
                "org.opencontainers.image.version": "1.0.0",
                "org.opencontainers.image.vendor": "FloatCTF",
                "org.opencontainers.image.source": (
                    "https://github.com/FloatCTF/floatctf-content"
                ),
                "io.floatctf.type": "challenge",
                "io.floatctf.id": "comment",
                "io.floatctf.category": "web",
                "io.floatctf.difficulty": "easy",
                "io.floatctf.version": "1.0.0",
                "io.floatctf.tags": "php,web",
            },
        )

    def test_image_labels_revision(self) -> None:
        challenge = content.load_content(VALID_FIXTURE, "challenges/comment")

        labels = content.image_labels(challenge, "deadbeef")
        self.assertEqual(labels["org.opencontainers.image.revision"], "deadbeef")

        with mock.patch.dict(os.environ, {"GITHUB_SHA": "cafebabe"}, clear=True):
            labels = content.image_labels(challenge)
        self.assertEqual(labels["org.opencontainers.image.revision"], "cafebabe")

    def test_image_labels_are_single_line(self) -> None:
        challenge = content.Content(
            id="multi",
            type=content.CONTENT_CHALLENGE,
            path=Path("challenges/multi"),
            meta={
                "name": "multi",
                "version": "1.0.0",
                "category": "web",
                "difficulty": "hard",
                "tags": ["a", "b"],
                "description": "line one\n\nline two",
            },
        )

        labels = content.image_labels(challenge)

        self.assertEqual(
            labels["org.opencontainers.image.description"], "line one line two"
        )
        for value in labels.values():
            self.assertNotIn("\n", value)

    def test_image_labels_keep_raw_content_id(self) -> None:
        item = content.Content(
            id="Cirno's perfect math class",
            type=content.CONTENT_CHALLENGE,
            path=Path("challenges/Cirno's perfect math class"),
            meta={
                "name": "Cirno's perfect math class",
                "version": "1.0.0",
                "category": "misc",
                "difficulty": "easy",
                "tags": ["misc"],
                "description": "fixture",
            },
        )

        labels = content.image_labels(item)

        # Labels keep the FloatCTF id; only the image repository is sanitized.
        self.assertEqual(labels["io.floatctf.id"], "Cirno's perfect math class")
        self.assertEqual(
            labels["org.opencontainers.image.title"], "Cirno's perfect math class"
        )
        self.assertEqual(
            content.image_ref(item),
            "floatctf/cirnos-perfect-math-class:challenge-v1.0.0",
        )

    def test_image_meta_github_output(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output = Path(tmp) / "github_output"

            result = quiet(
                content.main,
                [
                    "image-meta",
                    "challenges/comment",
                    "--root",
                    str(VALID_FIXTURE),
                    "--github-output",
                    str(output),
                    "--revision",
                    "deadbeef",
                ],
            )

            self.assertEqual(result, 0)

            text = output.read_text(encoding="utf-8")
            self.assertIn("image=floatctf/comment:challenge-v1.0.0\n", text)
            self.assertIn("context=challenges/comment/src\n", text)
            self.assertIn("labels<<EOF\n", text)
            self.assertTrue(text.endswith("EOF\n"))
            self.assertIn("org.opencontainers.image.revision=deadbeef\n", text)

    def test_changed_github_output_is_single_line(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output = Path(tmp) / "github_output"

            result = quiet(
                content.main,
                [
                    "changed",
                    "--all",
                    "--dockerfile-only",
                    "--root",
                    str(VALID_FIXTURE),
                    "--github-output",
                    str(output),
                ],
            )

            self.assertEqual(result, 0)
            self.assertEqual(
                output.read_text(encoding="utf-8"),
                'paths=["challenges/comment","gameboxes/comment"]\n',
            )


# ---------------------------------------------------------------------------
# 10. changed path detection
# ---------------------------------------------------------------------------


class ChangedTests(unittest.TestCase):
    def test_content_paths_filters_sorts_and_dedupes(self) -> None:
        names = [
            "challenges/comment/src/index.php",
            "challenges/comment/meta.toml",
            "challenges/comment/README.md",
            "gameboxes/foo/meta.toml",
            "events/freshcup.toml",
            "scripts/content.py",
            "scripts/tests/fixtures/valid/challenges/comment/meta.toml",
            "docs/freshcup.md",
            "README.md",
            "catalog.json",
        ]

        self.assertEqual(
            content.content_paths(names),
            ["challenges/comment", "gameboxes/foo"],
        )

    def test_content_paths_handles_spaces_and_quotes(self) -> None:
        names = [
            "challenges/Cirno's perfect math class/src/Dockerfile",
            "challenges/Cirno's perfect math class/meta.toml",
        ]

        self.assertEqual(
            content.content_paths(names),
            ["challenges/Cirno's perfect math class"],
        )

    def test_content_paths_ignores_non_content(self) -> None:
        self.assertEqual(
            content.content_paths(
                ["events/a.toml", "challenges", "challenges/", "gameboxes/x"]
            ),
            ["gameboxes/x"],
        )

    def test_find_changed_requires_revisions(self) -> None:
        with self.assertRaises(content.ContentError):
            content.find_changed(VALID_FIXTURE)

    def test_find_changed_dockerfile_filter(self) -> None:
        self.assertEqual(
            content.find_changed(VALID_FIXTURE, all_content=True),
            ["challenges/comment", "challenges/cookie", "gameboxes/comment"],
        )
        self.assertEqual(
            content.find_changed(
                VALID_FIXTURE, all_content=True, dockerfile_only=True
            ),
            ["challenges/comment", "gameboxes/comment"],
        )


@unittest.skipUnless(shutil.which("git"), "git is required")
class ChangedGitTests(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self._git("init", "-q")

        self.write("challenges/comment/meta.toml", 'name = "comment"\n')
        self.write("challenges/comment/src/Dockerfile", "FROM scratch\n")
        self.write("gameboxes/box/meta.toml", 'name = "box"\n')
        self.write("events/freshcup.toml", 'id = "freshcup"\n')
        self.write("README.md", "root\n")

        self.commit("one")
        self.base = self.rev("HEAD")

        self.write("challenges/comment/src/Dockerfile", "FROM busybox\n")
        self.write("gameboxes/box/README.md", "docs only\n")
        self.write("events/freshcup.toml", 'id = "freshcup"\n# changed\n')
        self.commit("two")
        self.head = self.rev("HEAD")

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def _git(self, *args: str) -> str:
        result = subprocess.run(
            ["git", "-C", str(self.root), *args],
            check=True,
            capture_output=True,
            text=True,
            env={
                **os.environ,
                "GIT_AUTHOR_NAME": "test",
                "GIT_AUTHOR_EMAIL": "test@example.com",
                "GIT_COMMITTER_NAME": "test",
                "GIT_COMMITTER_EMAIL": "test@example.com",
            },
        )
        return result.stdout.strip()

    def rev(self, reference: str) -> str:
        return self._git("rev-parse", reference)

    def write(self, relative: str, text: str) -> None:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def commit(self, message: str) -> None:
        self._git("add", "-A")
        self._git("commit", "-q", "-m", message)

    def test_diff_detects_src_changes_only(self) -> None:
        self.assertEqual(
            content.find_changed(self.root, self.base, self.head),
            ["challenges/comment", "gameboxes/box"],
        )
        self.assertEqual(
            content.find_changed(
                self.root, self.base, self.head, dockerfile_only=True
            ),
            ["challenges/comment"],
        )

    def test_events_and_scripts_do_not_trigger_builds(self) -> None:
        self.write("scripts/content.py", "# changed\n")
        self.commit("scripts")
        scripts_head = self.rev("HEAD")

        self.assertEqual(
            content.find_changed(self.root, self.head, scripts_head, dockerfile_only=True),
            [],
        )

    def test_zero_base_builds_everything(self) -> None:
        self.assertEqual(
            content.find_changed(self.root, "0" * 40, self.head),
            ["challenges/comment", "gameboxes/box"],
        )

    def test_deleted_content_is_not_scheduled_for_build(self) -> None:
        shutil.rmtree(self.root / "challenges" / "comment")
        self.commit("delete comment")
        head = self.rev("HEAD")

        self.assertEqual(
            content.find_changed(self.root, self.head, head, dockerfile_only=True),
            [],
        )


if __name__ == "__main__":
    unittest.main()
