name = "Android_reverse"
version = "1.0.0"
author = "ablklice@gmail.com"
category = "reverse"
description = "简单的android逆向"

# Optional: 显式 safe_name；缺省由 name 派生（派生失败时必须显式提供）
# safe_name = "xxx"

attachment = "attachment/Android_reverse.apk"

[flag]
type = "static"
value = "flag{It_1S_@N_3asY_@nDr0)I)1|d}"
