name = "miku_flag"
version = "1.0.0"
author = "ablklice@gmail.com"
category = "misc"
description = "这图片好像缺点什么"

# Optional: 显式 safe_name；缺省由 name 派生（派生失败时必须显式提供）
# safe_name = "xxx"

attachment = "attachment/mikuflag.png"

[flag]
type = "static"
value = "flag{this_is_mikuflag}"
